### ISSUE TITLE
Cannot run template

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/template-old#3]
I might be doing it wrong, but I am not able to set it up properly:
```
vapor new TemplateTest --template=nodes-vapor/template
Error: backgroundExecute(6, [], [39, 48, 48, 48, 10, 39])
```

**Comment by vzsg** [comment]
I'm also having trouble with creating a new project from the template like this, even though it should work (judging by the [new command's implementation](https://github.com/vapor/toolbox/blob/1.0.3/Sources/VaporToolbox/New.swift#L103)).

As a workaround, this command runs successfully:

```
vapor new TemplateTest --template=https://github.com/nodes-vapor/template
```

**Comment by BrettRToomey** [comment]
@vzsg Yup, it's a toolbox bug, PR here: https://github.com/vapor/toolbox/pull/120
